server:
  port: 8762
spring:
  application:
    name: client
eureka:
  client:
    service-url:
      defaultZone: http://user:123456@localhost:8761/eureka/
  instance:
    lease-expiration-duration-in-seconds: 5

